apiVersion: v2
name: aws-credential-manager
description: A Helm chart for AWS Credential Manager
type: application
version: v2026.1.20
appVersion: v0.0.3
home: https://github.com/appscode-cloud
icon: https://cdn.appscode.com/images/products/bytebuilders/icons/android-icon-192x192.png
sources:
- https://github.com/appscode-cloud
maintainers:
- name: appscode
  email: support@appscode.com
