apiVersion: catalog.klusters.dev/v1alpha1
kind: CapiVersion
metadata:
  name: "1.30"
  labels:
    {{- include "capi-catalog.labels" . | nindent 4 }}
spec:
  capa:
    deployerImage: '{{ include "image.ghcr" (merge (dict "_repo" "appscode/capa-deployer") $) }}:v1.30'
    ebsCSIDriverVersion: "v1.30.0-eksbuild.1"
    certManagerVersion: "v1.15.3"
    gatewayAPIVersion: "v1.0.0"
  capg:
    deployerImage: '{{ include "image.ghcr" (merge (dict "_repo" "appscode/capg-deployer") $) }}:v1.30'
    certManagerVersion: "v1.15.3"
    gatewayAPIVersion: "v1.0.0"
  capz:
    deployerImage: '{{ include "image.ghcr" (merge (dict "_repo" "appscode/capz-deployer") $) }}:v1.30'
    certManagerVersion: "v1.15.3"
    gatewayAPIVersion: "v1.0.0"
  caph:
    deployerImage: '{{ include "image.ghcr" (merge (dict "_repo" "appscode/caph-deployer") $) }}:v1.30'
    certManagerVersion: "v1.15.3"
    gatewayAPIVersion: "v1.0.0"
